### PR TITLE
updated day 1 and 2 and expack for work without comp

### PR DESCRIPTION
**Pull request by Bfinity**

### CODE REVIEW

**Comment by kyleofori** [comment]
ExPack 1.0.1 + 1.0.2 looks pretty cool (took me a while to find your changes, but I did). I like the tech-free solutions. Some comments on ExPack 1.0.1:
* The image for question 3 (Elements) is kind of stretched out.
* For question 4, since there's no tech, I think it'd be better to say "write an article".

On ExPack 1.0.2, I might suggest including the web address of the official links in small text, in case these ExPacks have been printed out for students.

:100:

**Comment by kyleofori** [comment]
**Day 2** is looking good as well. Thanks for getting rid of the GitHub slides and adding the notes to that first Standup slide.

In the HTML slide about structure (24), I wrote about things like newspaper and Facebook. I was thinking screenshots could help the visual learners, so I'll send some over; we could make those slides 25 and 26.

image
image

**Comment by Bfinity** [comment]
Updated.

**Comment by kyleofori** [comment]
E-mailed you some final changes to the Ex-Pack (didn't want to try all this GitHub magic). Once those are uploaded here, then I'll merge this as well!

**Comment by kyleofori** [comment]
Just so everyone else can see--I'd like the final ExPack 1.0.1 question 1 about elements to have this image.
elementstab

**Comment by Bfinity** [comment]
Ok. I'll add it. I might need to cut off the top... is that okay?

**Comment by kyleofori** [comment]
Yeah, no problem. Let me know once it's up!

**Pull request merged**
